name: GFT
version: ${project.version}
author: Aurium
main: com.elytraforce.gunfight.Main
depend: [SlimeWorldManager, Vault]
api-version: 1.15
commands:
  gft:
    description: The main command for Gunfight Tactics.
    aliases: []
  duelskit:
    description: Used to create and delete kits for Gunfight Tactics.
  quit:
    description: Quit a duels game