name: ${project.name}
version: ${project.version}
author: magicmq
main: dev.magicmq.duels.Duels
depend: [SlimeWorldManager, Vault]
api-version: 1.15
commands:
  duels:
    description: The main command for Duels.
    aliases: []
  duelskit:
    description: Used to create and delete kits for Duels.
  quit:
    description: Quit a duels game